baseURL: https://www.ehutch.net/
languageCode: "en-us"
title: "Eric Hutchinson's Website"
disableKinds:
- RSS
- taxonomy
- taxonomyTerm

minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
