baseURL: https://www.ehutch.net/
languageCode: "en-us"
title: "Eric Hutchinson"
disableKinds:
- RSS
- taxonomy

params:
  images:
  - about/profile.png

minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
