baseURL: https://www.ehutch.net/
languageCode: "en-us"
title: "Eric Hutchinson"
disableKinds:
- RSS
- taxonomy

params:
  images:
  - about/profile.png
  umami:
    url: https://data.geek-s.top/script.js
    site_id: 21db9f18-1e5b-4837-ae6d-f5b1e1f53e6c

minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
